name: CI Checks for aiobookoo

on:
  push:
    branches: [ main ] # Or your primary development branch
  pull_request:
    branches: [ main ] # Or your primary development branch
  workflow_dispatch: # Allows manual triggering

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  lint-type-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]  # Installs package and dev dependencies
          pip install ruff mypy # Ensure these are explicitly installed for the workflow

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Ruff Formatter Check
        run: ruff format --check .

      - name: Run MyPy Type Checker
        run: mypy --config-file=mypy.ini aiobookoov2/

      - name: Run Pytest
        run: pytest tests/
